services:
  dev:
    build: ./back
    container_name: git_handshakes_dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: sleep infinity
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - back
      - front

  back:
    build: ./back
    working_dir: /app
    volumes:
      - ./back:/app
    command: cargo watch -x run
    ports:
      - "3000:3000"

  front:
    build: ./front
    working_dir: /app
    volumes:
      - ./front:/app
    command: npm run dev
    ports:
      - "5173:5173"