FROM rust:1.94

ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID jehan \
    && useradd -m -u $USER_UID -g $USER_GID -s /bin/bash jehan

ENV CARGO_HOME=/app/.cargo
ENV RUSTUP_HOME=/app/.rustup

RUN mkdir -p /app/.cargo /app/.rustup

RUN rustup default stable
RUN cargo install cargo-edit

WORKDIR /app

COPY Cargo.toml Cargo.lock* ./
COPY src ./src

RUN cargo fetch

RUN chown -R jehan:jehan /app

COPY --chown=jehan:jehan . .

RUN cargo build

USER jehan

CMD ["cargo", "run"]